const colors = {
  black: "#f00",
  white: "#f00",
  red: "#f00",
  orange: "#f00",
  lightOrange: "#f00",
  yellow: "#f00",
  green: "#f00",
  blue: "#f00",
  teal: "#f00",
  pink: "#f00",
  purple: "#f00",
  gray: "#f00",
  border: "#f00",
  "gray-dark": "#f00",
  grayLight: "#f00",
  "gray-lighter": "#f00",
  "gray-lightest": "#f00",
  brightGrey: "#f00",
  darkGrey: "#f00",
  lightGrey: "#f00",
  lightestGrey: "#f00",
  mediumGrey: "#f00",
  grey: "#f00",
  greyDark: "#f00",
  greyAlpha: "rgba(227, 233, 243, 0.5)",
  lightestBlue: "#f00",
  lightBlue: "#f00",
  mediumBlue: "#f00",
  darkBlue: "#f00",
  pale: "#f00",
  content: {
    background: "#f00",
    "background-alpha": "rgba(14, 22, 34, 0.02)",
  },
  leftMenu: {
    "link-hover": "#f00",
    "link-color": "#f00",
    "title-color": "#f00",
    "background-header-link": "#f00",
  },
  strapi: {
    "gray-light": "#f00",
    gray: "#f00",
    "blue-darker": "#f00",
    "blue-dark": "#f00",
    blue: "#f00",
  },
};

export default colors;
